export const modalActions = {
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  LOADED: "LOADED",
  LOADING: "LOADING",
  SET_CHILDREN: "SET_CHILDREN",
  SET_CLOSE_HANDLE: "SET_CLOSE_HANDLE",
  SET_SUBMIT_HANDLE: "SET_SUBMIT_HANDLE",
};
